# yaml-language-server: $schema=http://json.schemastore.org/base
# yaml-language-server: disable
# golangci-lint v1 configuration - schema validation disabled
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - gosec
    - misspell
